export const REQUEST_MOVIE_GROUP = 'movies.REQUEST_MOVIE_GROUP';
export const REQUEST_MOVIE_GENRE = 'movies.REQUEST_MOVIE_GENRE';
export const APPEND_TO_GROUP_MOVIE_LIST = 'movies.APPEND_TO_GROUP_MOVIE_LIST';
export const APPEND_TO_GENRE_MOVIE_LIST = 'movies.APPEND_TO_GENRE_MOVIE_LIST';
export const REQUEST_MOVIE = 'movies.REQUEST_MOVIE';
export const SAVE_MOVIE = 'movies.SAVE_MOVIE';
export const CHANGE_BACKGROUND = 'movies.CHANGE_BACKGROUND';
