export const REQUEST_MOVIE_SEARCH = 'search.REQUEST_MOVIE_SEARCH';
export const REPLACE_SEARCH_MOVIE_LIST = 'search.REPLACE_SEARCH_MOVIE_LIST';
export const SET_SEARCH_QUERY = 'search.SET_SEARCH_QUERY';
