export const REQUEST_MOVIE_SEARCH = 'search.REQUEST_MOVIE_SEARCH';
export const REPLACE_SEARCH_MOVIE_LIST = 'search.REPLACE_SEARCH_MOVIE_LIST';
export const SET_SEARCH_QUERY = 'search.SET_SEARCH_QUERY';
export const SET_SEARCH_RESULTS_LOADING = 'movies.SET_SEARCH_RESULTS_LOADING';
export const SET_SEARCH_RESULTS_LOADED = 'movies.SET_SEARCH_RESULTS_LOADED';
